apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-multiverse-frontend-recreate
  labels:
    app.kubernetes.io/name: ty-multiverse-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate  # 先刪除所有舊 pod，再建立新 pod
  selector:
    matchLabels:
      app.kubernetes.io/name: ty-multiverse-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ty-multiverse-frontend
    spec:
      containers:
      - name: ty-multiverse-frontend
        image: papakao/ty-multiverse-frontend:latest
        ports:
        - containerPort: 4321
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: PUBLIC_DECKOFCARDS_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_DECKOFCARDS_URL
        - name: PUBLIC_TYMB_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_TYMB_URL
        - name: PUBLIC_SSO_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_SSO_URL
        - name: PUBLIC_FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_FRONTEND_URL
        - name: PUBLIC_PEOPLE_IMAGE_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_PEOPLE_IMAGE_URL
        - name: PUBLIC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_CLIENT_ID
        - name: PUBLIC_REALM
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_REALM
        - name: PUBLIC_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-frontend-secrets
              key: PUBLIC_API_BASE_URL
